### ISSUE TITLE
[Bug] Creating a movie without screenings

### ISSUE THREAD

**Issue by meretamal** [IIC3745-Testing-Grupo3/IIC3745-Grupo3-ProyectoB#18]
Currently you can create a movie without screenings, which is not the desired behavior.

For this I think that we should disable every button in the new movie form, until certain requirements are fulfilled.

Also, it's necessary to manage this in the backend, not allowing to create the movie if the request receives 0 screenings to add.

**Comment by arpincheira** [comment]
Solved, thanks for noticing it.
